In [1]:
import sys
sys.path.append('../')

In [2]:
from src.config import DB_CONFIG
from src.model.eq_accountant import EQAccountant
from src.model.t24_accountant import T24Accountant

In [3]:
eq_accountant = EQAccountant(DB_CONFIG)
t24_accountant = T24Accountant(DB_CONFIG)

2025-06-17 08:25:58,581 - INFO - EQAccountant initialized with logging enabled: True
2025-06-17 08:25:58,600 - INFO - T24Accountant initialized with logging enabled: True

In [4]:
eq_account = '5820061625500'
t24_account = '2010284298'
year = '2024'

In [5]:
t24_accountant.get_accountant_transactions(t24_account, year)

2025-06-17 08:26:01,495 - INFO - Starting to retrieve T24 accountant's transactions for account: 2010284298, year: 2024

Connection established successfully.

2025-06-17 08:26:49,629 - INFO - Successfully executed query:
            SELECT
                T24_ACCOUNTANT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                --EQ_T24.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
                'NA' AS EQ_ACCOUNT,
                --EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                'NA' AS ORACLE_ACCOUNT,
                T24_ACCOUNTANT.TRANS_REFERENCE AS TRANSACTION_REF,
                'NA' AS TRANSACTION_SEQ,
                T24_ACCOUNTANT.VALUE_DATE AS TRANSACTION_DATE,
                T24_ACCOUNTANT.SYSTEM_DATE_TIME AS TRANSACTION_DATE_TS,
                T24_ACCOUNTANT.CURRENCY AS TRANSACTION_CURRENCY,
                T24_ACCOUNTANT.AMOUNT_LCY AS TRANSACTION_AMOUNT_LCY,
                T24_ACCOUNTANT.AMOUNT_FCY AS TRANSACTION_AMOUNT_FCY,
                'NA' AS TRANSACTION_AMOUNT,
                T24_ACCOUNTANT.TRANSACTION_CODE AS TRANSACTION_CODE_ATB,
                'NA' AS TRANSACTION_DESC_ATB,
                T24_ACCOUNTANT.SYSTEM_ID AS APP_SOURCE_CODE,
                'T24' AS ACCOUNTANT_SOURCE
            FROM [MISDW].[TRG].[T24_FATB_STMT_ENTRY_2024] AS T24_ACCOUNTANT
            --INNER JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24 ON EQ_T24.GLOBUS_ACCT_NUMBER = T24_ACCOUNTANT.ACCOUNT_NUMBER
            --INNER JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            WHERE
                T24_ACCOUNTANT.ACCOUNT_NUMBER = '2010284298'
                AND SUBSTRING(T24_ACCOUNTANT.VALUE_DATE, 1, 4) = '2024'

2025-06-17 08:27:15,835 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                T24_ACCOUNTANT.ACCOUNT_NUMBER AS T24_ACCOUNT,
                --EQ_T24.ALTERNATIVE_NUMBER AS EQ_ACCOUNT,
                'NA' AS EQ_ACCOUNT,
                --EQ_ORACLE.NEEAN AS ORACLE_ACCOUNT,
                'NA' AS ORACLE_ACCOUNT,
                T24_ACCOUNTANT.TRANS_REFERENCE AS TRANSACTION_REF,
                'NA' AS TRANSACTION_SEQ,
                T24_ACCOUNTANT.VALUE_DATE AS TRANSACTION_DATE,
                T24_ACCOUNTANT.SYSTEM_DATE_TIME AS TRANSACTION_DATE_TS,
                T24_ACCOUNTANT.CURRENCY AS TRANSACTION_CURRENCY,
                T24_ACCOUNTANT.AMOUNT_LCY AS TRANSACTION_AMOUNT_LCY,
                T24_ACCOUNTANT.AMOUNT_FCY AS TRANSACTION_AMOUNT_FCY,
                'NA' AS TRANSACTION_AMOUNT,
                T24_ACCOUNTANT.TRANSACTION_CODE AS TRANSACTION_CODE_ATB,
                'NA' AS TRANSACTION_DESC_ATB,
                T24_ACCOUNTANT.SYSTEM_ID AS APP_SOURCE_CODE,
                'T24' AS ACCOUNTANT_SOURCE
            FROM [MISDW].[TRG].[T24_FATB_STMT_ENTRY_2024] AS T24_ACCOUNTANT
            --INNER JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24 ON EQ_T24.GLOBUS_ACCT_NUMBER = T24_ACCOUNTANT.ACCOUNT_NUMBER
            --INNER JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            WHERE
                T24_ACCOUNTANT.ACCOUNT_NUMBER = '2010284298'
                AND SUBSTRING(T24_ACCOUNTANT.VALUE_DATE, 1, 4) = '2024'

2025-06-17 08:27:15,840 - INFO - Query executed successfully. T24 accountant's transactions retrieved for the account.
2025-06-17 08:27:15,841 - INFO - Closing database connection.
2025-06-17 08:27:15,855 - INFO - Returning cleaned DataFrame.

Connection closed.

In [6]:
t24_accountant.accountant_transactions

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT_LCY,TRANSACTION_AMOUNT_FCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE_CODE,ACCOUNTANT_SOURCE
0,2010284298,NA,NA,FT241490RDSX0PLS,NA,20240528,20240528074437608,TND,-103.687,None,NA,8054,NA,FT,T24
1,2010284298,NA,NA,FT2403106TKHXT1R,NA,20240131,20240131120033495,TND,-70.000,None,NA,8439,NA,FT,T24
2,2010284298,NA,NA,FT2400805FHHY13M,NA,20240108,20240106121535497,TND,-201.600,None,NA,8427,NA,FT,T24
3,2010284298,NA,NA,FT240290NDW8XJKD,NA,20240129,20240128085157988,TND,-100.000,None,NA,8427,NA,FT,T24
4,2010284298,NA,NA,FT240261046DBY35,NA,20240126,20240126104553048,TND,-16.000,None,NA,8010,NA,FT,T24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,2010284298,NA,NA,FT2433011S5WK1PR,NA,20241125,20241125052808129,TND,-400.000,None,NA,8427,NA,FT,T24
152,2010284298,NA,NA,FT243090XM57X0J7,NA,20241104,20241104161501441,TND,-100.000,None,NA,8427,NA,FT,T24
153,2010284298,NA,NA,FT2436011G6THWPP,NA,20241225,20241225101315473,TND,-100.000,None,NA,8427,NA,FT,T24
154,2010284298,NA,NA,FT243410GY8SSXXT,NA,20241206,20241206160408275,TND,-100.000,None,NA,8427,NA,FT,T24
155,2010284298,NA,NA,FT2435513XC27HQS,NA,20241220,20241220153542631,TND,-16.000,None,NA,8010,NA,FT,T24

In [7]:
eq_accountant.get_accountant_transactions(eq_account, year)

2025-06-17 08:28:27,231 - INFO - Starting to retrieve accountant's transactions for account: 5820061625500, year: 2024

Connection established successfully.

2025-06-17 08:28:55,861 - INFO - Successfully executed query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE,
                'EQ' AS ACCOUNTANT_SOURCE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5820061625500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2024'

2025-06-17 08:30:39,025 - INFO - Successfully converted query result to DataFrame for query:
            SELECT
                TRIM(EQ_T24.GLOBUS_ACCT_NUMBER) AS T24_ACCOUNT,
                TRIM(EQ_T24.ALTERNATIVE_NUMBER) AS EQ_ACCOUNT,
                TRIM(EQ_ORACLE.NEEAN) AS ORACLE_ACCOUNT,
                TRIM(CAST(EQ_ACCOUNTANT.SADRF AS VARCHAR)) AS TRANSACTION_REF,
                EQ_ACCOUNTANT.SAPSQ AS TRANSACTION_SEQ,
                TRIM(CAST(EQ_ACCOUNTANT.SAPOD AS VARCHAR)) AS TRANSACTION_DATE,
                FORMAT(EQ_ACCOUNTANT.SATSTP, 'yyyy-MM-dd HH.mm') AS TRANSACTION_DATE_TS,
                EQ_ACCOUNTANT.SACCY AS TRANSACTION_CURRENCY,
                EQ_ACCOUNTANT.SAAMA / POWER(10, CURRENCY.NO_OF_DECIMALS) AS TRANSACTION_AMOUNT,
                EQ_ACCOUNTANT.SATCD AS TRANSACTION_CODE_ATB,
                EQA_TRANSACTION_CODE.CTTCN AS TRANSACTION_DESC_ATB,
                EQ_ACCOUNTANT.SAPBR AS APP_SOURCE_CODE,
                'EQ' AS ACCOUNTANT_SOURCE
            FROM [MISDW].[TRG].[EQA_POSTINGS_THX] AS EQ_ACCOUNTANT
            LEFT JOIN [MISDW].[TRG].[EQA_TRANSACTION_CODE] AS EQA_TRANSACTION_CODE
                ON EQA_TRANSACTION_CODE.CTTCD = EQ_ACCOUNTANT.SATCD
            LEFT JOIN [MISDW].[TRG].[T24_FATB_ALTERNATE_ACCO000] AS EQ_T24
                ON EQ_T24.ALTERNATIVE_NUMBER = EQ_ACCOUNTANT.SAAB + EQ_ACCOUNTANT.SAAN + EQ_ACCOUNTANT.SAAS
            LEFT JOIN [MISDW].[TRG].[EQA_ACC_EXTERNAL_ACCOUNT_NUMBER] AS EQ_ORACLE
                ON EQ_ORACLE.NEAB + EQ_ORACLE.NEAN + EQ_ORACLE.NEAS = EQ_T24.ALTERNATIVE_NUMBER
            LEFT JOIN [MISDW].[TRG].[T24_FBNK_CURRENCY] AS CURRENCY
                ON CURRENCY.CURRENCY_CODE = EQ_ACCOUNTANT.SACCY
            WHERE
                EQ_T24.ALTERNATIVE_NUMBER = '5820061625500'
                AND '20' + SUBSTRING(CONVERT(VARCHAR, EQ_ACCOUNTANT.SAPOD), 2, 2) = '2024'

2025-06-17 08:30:39,030 - INFO - Query executed successfully. Accountant's transactions retrieved for the account.
2025-06-17 08:30:39,032 - INFO - Closing database connection.
2025-06-17 08:30:39,038 - INFO - Returning cleaned DataFrame.

Connection closed.

In [8]:
t24_accountant.accountant_transactions.loc[ t24_accountant.accountant_transactions['APP_SOURCE_CODE'] == 'TT']

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT_LCY,TRANSACTION_AMOUNT_FCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE_CODE,ACCOUNTANT_SOURCE
34,2010284298,NA,NA,TT242749T9C0,NA,20240930,20240930115914197,TND,-2500.000,None,NA,1013,NA,TT,T24
70,2010284298,NA,NA,TT242905FRKJ,NA,20241016,20241016120543094,TND,-3300.000,None,NA,1013,NA,TT,T24

In [9]:
eq_accountant.accountant_transactions.loc[ eq_accountant.accountant_transactions['APP_SOURCE_CODE'] == 'T24TL']

,T24_ACCOUNT,EQ_ACCOUNT,ORACLE_ACCOUNT,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_DATE,TRANSACTION_DATE_TS,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE_CODE,ACCOUNTANT_SOURCE
118,2010284298,5820061625500,0201119826975,TT242905FRKJ,441,1241016,None,TND,-3300.0000000000,067,Retrait Especes Meme Agence,T24TL,EQ
142,2010284298,5820061625500,0201119826975,TT242749T9C0,567,1240930,None,TND,-2500.0000000000,067,Retrait Especes Meme Agence,T24TL,EQ

In [10]:
import pandas as pd

In [11]:
eq_accountant.accountant_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   T24_ACCOUNT           185 non-null    object
 1   EQ_ACCOUNT            185 non-null    object
 2   ORACLE_ACCOUNT        185 non-null    object
 3   TRANSACTION_REF       185 non-null    object
 4   TRANSACTION_SEQ       185 non-null    object
 5   TRANSACTION_DATE      185 non-null    object
 6   TRANSACTION_DATE_TS   85 non-null     object
 7   TRANSACTION_CURRENCY  185 non-null    object
 8   TRANSACTION_AMOUNT    185 non-null    object
 9   TRANSACTION_CODE_ATB  185 non-null    object
 10  TRANSACTION_DESC_ATB  185 non-null    object
 11  APP_SOURCE_CODE       185 non-null    object
 12  ACCOUNTANT_SOURCE     185 non-null    object
dtypes: object(13)
memory usage: 18.9+ KB

In [19]:
pd.concat(
    [eq_accountant.accountant_transactions.loc[ eq_accountant.accountant_transactions['APP_SOURCE_CODE'] != 'T24TL'],
     t24_accountant.accountant_transactions.loc[ t24_accountant.accountant_transactions['APP_SOURCE_CODE'] == 'TT']],
    ignore_index=True
)[['T24_ACCOUNT', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB', 'TRANSACTION_DATE', 'TRANSACTION_REF', 'TRANSACTION_SEQ', 'TRANSACTION_CURRENCY', 'TRANSACTION_AMOUNT', 'TRANSACTION_AMOUNT_LCY', 'TRANSACTION_AMOUNT_FCY']]

,T24_ACCOUNT,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DATE,TRANSACTION_REF,TRANSACTION_SEQ,TRANSACTION_CURRENCY,TRANSACTION_AMOUNT,TRANSACTION_AMOUNT_LCY,TRANSACTION_AMOUNT_FCY
0,2010284298,@@O2,427,1240108,S001412291788,26489,TND,-201.6000000000,NaN,NaN
1,2010284298,@@O2,427,1240108,S001412291896,26569,TND,-201.6000000000,NaN,NaN
2,2010284298,@@O2,439,1240108,S075500048939,38969,TND,-273.0830000000,NaN,NaN
3,2010284298,@@O2,427,1240112,S200024721241,19365,TND,-50.0000000000,NaN,NaN
4,2010284298,DRHTR,010,1240625,25062024,1473,TND,-16.0000000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
180,2010284298,@@O2,427,1241212,S200024646869,4389,TND,-100.0000000000,NaN,NaN
181,2010284298,HR000,512,1241227,MT202416,2100,TND,2718.3660000000,NaN,NaN
182,2010284298,HR000,135,1241227,MT202416,2276,TND,-6.2500000000,NaN,NaN
183,2010284298,TT,1013,20240930,TT242749T9C0,NA,TND,NA,-2500.000,None
184,2010284298,TT,1013,20241016,TT242905FRKJ,NA,TND,NA,-3300.000,None

In [23]:
eq_accountant.accountant_transactions.columns

Index(['T24_ACCOUNT', 'EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'TRANSACTION_REF',
       'TRANSACTION_SEQ', 'TRANSACTION_DATE', 'TRANSACTION_DATE_TS',
       'TRANSACTION_CURRENCY', 'TRANSACTION_AMOUNT', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB', 'APP_SOURCE_CODE', 'ACCOUNTANT_SOURCE'],
      dtype='object')

In [24]:
t24_accountant.accountant_transactions.columns

Index(['T24_ACCOUNT', 'EQ_ACCOUNT', 'ORACLE_ACCOUNT', 'TRANSACTION_REF',
       'TRANSACTION_SEQ', 'TRANSACTION_DATE', 'TRANSACTION_DATE_TS',
       'TRANSACTION_CURRENCY', 'TRANSACTION_AMOUNT_LCY',
       'TRANSACTION_AMOUNT_FCY', 'TRANSACTION_AMOUNT', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB', 'APP_SOURCE_CODE', 'ACCOUNTANT_SOURCE'],
      dtype='object')

In [26]:
pd.concat(
    [eq_accountant.accountant_transactions.loc[ eq_accountant.accountant_transactions['APP_SOURCE_CODE'] != 'T24TL'],
     t24_accountant.accountant_transactions.loc[ t24_accountant.accountant_transactions['APP_SOURCE_CODE'] == 'TT']],
    ignore_index=True
).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   T24_ACCOUNT             185 non-null    object
 1   EQ_ACCOUNT              185 non-null    object
 2   ORACLE_ACCOUNT          185 non-null    object
 3   TRANSACTION_REF         185 non-null    object
 4   TRANSACTION_SEQ         185 non-null    object
 5   TRANSACTION_DATE        185 non-null    object
 6   TRANSACTION_DATE_TS     87 non-null     object
 7   TRANSACTION_CURRENCY    185 non-null    object
 8   TRANSACTION_AMOUNT      185 non-null    object
 9   TRANSACTION_CODE_ATB    185 non-null    object
 10  TRANSACTION_DESC_ATB    185 non-null    object
 11  APP_SOURCE_CODE         185 non-null    object
 12  ACCOUNTANT_SOURCE       185 non-null    object
 13  TRANSACTION_AMOUNT_LCY  2 non-null      object
 14  TRANSACTION_AMOUNT_FCY  0 non-null      object
dtypes: object(15)
memory usage: 21.8+ KB