In [1]:
import os
import pandas as pd

In [2]:
os.listdir('./')

['.ipynb_checkpoints',
 'accountant_trx.xlsx',
 'output.xlsx',
 'PP_code.xlsx',
 'TRANSACTION_CODE_EQA_T24.txt',
 'Untitled.ipynb']

In [3]:
trx_code = pd.read_excel('accountant_trx.xlsx')

In [6]:
trx_code.ACCOUNTANT_SOURCE.unique()

array(['EQ', 'T24'], dtype=object)

In [7]:
import numpy as np

In [8]:
# Apply zfill(3) for 'EQ' and zfill(4) for 'T24'
trx_code['TRANSACTION_CODE_ATB'] = np.where(
    trx_code['ACCOUNTANT_SOURCE'] == 'EQ',
    trx_code['TRANSACTION_CODE_ATB'].astype(str).str.zfill(3),
    trx_code['TRANSACTION_CODE_ATB'].astype(str).str.zfill(4)
)

In [23]:
trx_code

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2
0,EQ,T24TL,297,Comm.OPPOS EFFET,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
1,EQ,UAJL,920,Interets,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,EQ,@@CC,120,Remb avance placement,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EQ,TLVIR,010,Debit,IBANK,Virement,NaN,NaN,NaN,NaN,NaN
4,EQ,@@FM,401,Exchange Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4025,T24,TT,4241,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
4026,T24,TT,4240,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
4027,T24,TT,7278,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
4028,T24,TT,4244,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
4029,T24,TT,4243,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN

In [10]:
trx_code_eq_t24 = pd.read_csv('TRANSACTION_CODE_EQA_T24.txt', sep='\t', engine='python')
trx_code_eq_t24['TCDEQU'] = trx_code_eq_t24['TCDEQU'].astype(str).str.zfill(3)

In [ ]:
PP_code = pd.read_excel('PP_code.xlsx')

In [19]:
PP_code['TRANSACTION_CODE'] = PP_code.TRANSACTION_CODE.astype(str)

In [21]:
j1 = pd.merge(
    left=PP_code,
    right=trx_code_eq_t24,
    left_on='TRANSACTION_CODE',
    right_on='TCD24'
)

In [24]:
pd.merge(
    left=j1,
    right=trx_code,
    left_on='TCD24',
    right_on='TRANSACTION_CODE_ATB'
)

,TRANSACTION_CODE,TCD24,TCDEQU,T24DESC,AVFLG,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2
0,7085,7085,270,TVA/Commission ...,,T24,TT,7085,TVA,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
1,7585,7585,770,TVA/Commission ...,,T24,TT,7585,TVA,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN

In [3]:
trx_code = pd.read_excel('accountant_trx.xlsx')
trx_code['TRANSACTION_CODE_ATB'] = trx_code['TRANSACTION_CODE_ATB'].astype(str).str.zfill(3)

In [4]:
trx_code_eq_t24 = pd.read_csv('TRANSACTION_CODE_EQA_T24.txt', sep='\t', engine='python')
trx_code_eq_t24['TCDEQU'] = trx_code_eq_t24['TCDEQU'].astype(str).str.zfill(3)

In [6]:
pd.merge(
    left=trx_code.query("(ACCOUNTANT_SOURCE == 'EQ') & (OP_TYPE == 'Caisse') & (APP_SOURCE == 'Teller') & (APP_SOURCE_CODE == 'T24TL')"),
    right=trx_code_eq_t24,
    left_on='TRANSACTION_CODE_ATB',
    right_on='TCDEQU',
    indicator=True
).T

,0,1,2,3,4,5,6,7,8,9,...,252,253,254,255,256,257,258,259,260,261
ACCOUNTANT_SOURCE,EQ,EQ,EQ,EQ,EQ,EQ,EQ,EQ,EQ,EQ,...,EQ,EQ,EQ,EQ,EQ,EQ,EQ,EQ,EQ,EQ
APP_SOURCE_CODE,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL,...,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL,T24TL
TRANSACTION_CODE_ATB,297,001,001,001,001,001,001,001,001,001,...,260,260,260,260,260,260,260,260,260,260
TRANSACTION_DESC_ATB,Comm.OPPOS EFFET,Retrait Especes,Retrait Especes,Retrait Especes,Retrait Especes,Retrait Especes,Retrait Especes,Retrait Especes,Retrait Especes,Retrait Especes,...,Commission,Commission,Commission,Commission,Commission,Commission,Commission,Commission,Commission,Commission
APP_SOURCE,Teller,Teller,Teller,Teller,Teller,Teller,Teller,Teller,Teller,Teller,...,Teller,Teller,Teller,Teller,Teller,Teller,Teller,Teller,Teller,Teller
OP_TYPE,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse,...,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse,Caisse
Categorie_de_transaction,code relatif aux commissions / frais / intérêts,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,code affectant directement le compte client (d...,...,code relatif aux commissions / frais / intérêts,code relatif aux commissions / frais / intérêts,code relatif aux commissions / frais / intérêts,code relatif aux commissions / frais / intérêts,code relatif aux commissions / frais / intérêts,code relatif aux commissions / frais / intérêts,code relatif aux commissions / frais / intérêts,code relatif aux commissions / frais / intérêts,code relatif aux commissions / frais / intérêts,code relatif aux commissions / frais / intérêts
TRANSACTION_CODE_GOAML,NaN,B200,B200,B200,B200,B200,B200,B200,B200,B200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRANSACTION_DESC_GOAML,NaN,Retrait espèces,Retrait espèces,Retrait espèces,Retrait espèces,Retrait espèces,Retrait espèces,Retrait espèces,Retrait espèces,Retrait espèces,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FUND_CODE_1,NaN,A,A,A,A,A,A,A,A,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FUND_CODE_2,NaN,K,K,K,K,K,K,K,K,K,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TCD24,1216,1017,1018,1019,1021,1024,1025,1027,1028,1116,...,1240,1241,1242,1243,1259,4241,4240,7278,4244,4243
TCDEQU,297,001,001,001,001,001,001,001,001,001,...,260,260,260,260,260,260,260,260,260,260
T24DESC,Comm.OPPOS EFFET/Comm sur Leve oppostion e ...,Retrait Ch}que/Retrait especes en devis ...,Retrait esp}ces/Retrait especes mme age ...,Retrait esp}ces/Retrait especes mme age ...,Retrait esp}ces/Retrait especes en devis ...,Retrait esp}ces ...,Retrait esp}ces/CHANGE MANUEL VENTE ...,Retrait esp}ces/CHANGE MANUEL ACHAT ...,Retrait esp}ces/CHANGE MANUEL ACHAT ...,Retrait esp}ces ...,...,Commission ...,Commission ...,Commission ...,Commission ...,Commission ...,Frais Rech Docu Archiv ...,Deliv Attes CR ...,Frais Rech Docu Cpt Clt ...,Comm Image CHQ ...,Comm Image Eff ...
AVFLG,0,,,,,,,,,,...,,,,,,,,,,
_merge,both,both,both,both,both,both,both,both,both,both,...,both,both,both,both,both,both,both,both,both,both

In [7]:
r = pd.merge(
    left=trx_code.query("(ACCOUNTANT_SOURCE == 'EQ') & (OP_TYPE == 'Caisse') & (APP_SOURCE == 'Teller') & (APP_SOURCE_CODE == 'T24TL')"),
    right=trx_code_eq_t24,
    left_on='TRANSACTION_CODE_ATB',
    right_on='TCDEQU',
    how='inner',
    indicator=True
)

In [33]:
r.columns

Index(['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB', 'APP_SOURCE', 'OP_TYPE',
       'Categorie_de_transaction', 'TRANSACTION_CODE_GOAML',
       'TRANSACTION_DESC_GOAML', 'FUND_CODE_1', 'FUND_CODE_2', 'TCD24',
       'TCDEQU', 'T24DESC', 'AVFLG', '_merge'],
      dtype='object')

In [8]:
r['ACCOUNTANT_SOURCE'] = 'T24'
r['APP_SOURCE_CODE'] = 'TT'

r.drop(columns=['TRANSACTION_CODE_ATB'], inplace=True)

r.rename(columns={'TCD24': 'TRANSACTION_CODE_ATB'}, inplace=True)

In [9]:
r[['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB', 'APP_SOURCE', 'OP_TYPE',
       'Categorie_de_transaction', 'TRANSACTION_CODE_GOAML',
       'TRANSACTION_DESC_GOAML', 'FUND_CODE_1', 'FUND_CODE_2']]

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2
0,T24,TT,1216,Comm.OPPOS EFFET,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
1,T24,TT,1017,Retrait Especes,Teller,Caisse,code affectant directement le compte client (d...,B200,Retrait espèces,A,K
2,T24,TT,1018,Retrait Especes,Teller,Caisse,code affectant directement le compte client (d...,B200,Retrait espèces,A,K
3,T24,TT,1019,Retrait Especes,Teller,Caisse,code affectant directement le compte client (d...,B200,Retrait espèces,A,K
4,T24,TT,1021,Retrait Especes,Teller,Caisse,code affectant directement le compte client (d...,B200,Retrait espèces,A,K
...,...,...,...,...,...,...,...,...,...,...,...
257,T24,TT,4241,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
258,T24,TT,4240,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
259,T24,TT,7278,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
260,T24,TT,4244,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
261,T24,TT,4243,Commission,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN

In [10]:
yy = pd.concat([
    trx_code,
    r[['ACCOUNTANT_SOURCE', 'APP_SOURCE_CODE', 'TRANSACTION_CODE_ATB',
       'TRANSACTION_DESC_ATB', 'APP_SOURCE', 'OP_TYPE',
       'Categorie_de_transaction', 'TRANSACTION_CODE_GOAML',
       'TRANSACTION_DESC_GOAML', 'FUND_CODE_1', 'FUND_CODE_2']]
], ignore_index=True)

In [58]:
yy.query("ACCOUNTANT_SOURCE == 'EQ'")

,ACCOUNTANT_SOURCE,APP_SOURCE_CODE,TRANSACTION_CODE_ATB,TRANSACTION_DESC_ATB,APP_SOURCE,OP_TYPE,Categorie_de_transaction,TRANSACTION_CODE_GOAML,TRANSACTION_DESC_GOAML,FUND_CODE_1,FUND_CODE_2
0,EQ,T24TL,297,Comm.OPPOS EFFET,Teller,Caisse,code relatif aux commissions / frais / intérêts,NaN,NaN,NaN,NaN
1,EQ,UAJL,920,Interets,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,EQ,@@CC,120,Remb avance placement,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EQ,TLVIR,10,Debit,IBANK,Virement,NaN,NaN,NaN,NaN,NaN
4,EQ,@@FM,401,Exchange Delivery,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3762,EQ,TCTL3,223,Paiement effet,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3763,EQ,TCTL0,510,Credit,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3764,EQ,UDHD,878,Transf Sld Data cleaning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3765,EQ,USR6,10,Debit,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3766,EQ,UAZN1,598,Credits divers,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
yy.to_excel('output.xlsx', index=False)

In [26]:
trx_code.query("(ACCOUNTANT_SOURCE == 'EQ') & (OP_TYPE == 'Caisse') & (APP_SOURCE == 'Teller') & (APP_SOURCE_CODE == 'T24TL')").info()

<class 'pandas.core.frame.DataFrame'>
Index: 116 entries, 0 to 3759
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ACCOUNTANT_SOURCE         116 non-null    object
 1   APP_SOURCE_CODE           116 non-null    object
 2   TRANSACTION_CODE_ATB      116 non-null    int64
 3   TRANSACTION_DESC_ATB      116 non-null    object
 4   APP_SOURCE                116 non-null    object
 5   OP_TYPE                   116 non-null    object
 6   Categorie_de_transaction  95 non-null     object
 7   TRANSACTION_CODE_GOAML    51 non-null     object
 8   TRANSACTION_DESC_GOAML    43 non-null     object
 9   FUND_CODE_1               51 non-null     object
 10  FUND_CODE_2               51 non-null     object
dtypes: int64(1), object(10)
memory usage: 10.9+ KB

In [25]:
trx_code.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3768 entries, 0 to 3767
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ACCOUNTANT_SOURCE         3768 non-null   object
 1   APP_SOURCE_CODE           3754 non-null   object
 2   TRANSACTION_CODE_ATB      3768 non-null   int64
 3   TRANSACTION_DESC_ATB      3767 non-null   object
 4   APP_SOURCE                332 non-null    object
 5   OP_TYPE                   362 non-null    object
 6   Categorie_de_transaction  417 non-null    object
 7   TRANSACTION_CODE_GOAML    116 non-null    object
 8   TRANSACTION_DESC_GOAML    105 non-null    object
 9   FUND_CODE_1               116 non-null    object
 10  FUND_CODE_2               116 non-null    object
dtypes: int64(1), object(10)
memory usage: 323.9+ KB